# Site settings
title: nathan's notes
description: "a blog."
url: "https://nathanberryhill.org/blog/"
author:
  name: "Nathan Berryhill"
  email: "contact@nathanberryhill.org"
  url: "https://nathanberryhill.org"

# Build settings
baseurl: /blog/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: ""

# Options
custom_header: false
custom_nav_footer: false
reverse: false
